apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: htcondor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "htcondor-chart.serviceAccountName" . }}