apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pool-password
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.pool_password would have worked too.
  password: {{ index (lookup "v1" "Secret" .Release.Namespace (print .Release.Name "-pool-password")).data "password" }}
  {{ end }}
